import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "./assets/global.css";
import CardLayout from "./components/CardLayout.vue";
const app = createApp(App);
app.use(store);
app.use(router);
app.component("card-layout", CardLayout);
app.mount("#app");
